// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CtaPulseController from "./cta_pulse_controller"
application.register("cta-pulse", CtaPulseController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RevealController from "./reveal_controller"
application.register("reveal", RevealController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)
