EnableDefaultLinters: true
Linters:
  FinalNewline:
    Enabled: true
  SpaceInHtmlTag:
    Enabled: true
  RightTrim:
    Enabled: true
  SelfClosingTag:
    Enabled: true
  HardCodedString:
    Enabled: false

